#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : grpcio
Version  : 1.10.1
Release  : 3
URL      : https://pypi.python.org/packages/6b/30/8cab00b2342a9c7946174261ae220ddfb4e30d8a00b67d077c1829724617/grpcio-1.10.1.tar.gz
Source0  : https://pypi.python.org/packages/6b/30/8cab00b2342a9c7946174261ae220ddfb4e30d8a00b67d077c1829724617/grpcio-1.10.1.tar.gz
Summary  : HTTP/2-based RPC framework
Group    : Development/Tools
License  : Apache-2.0
Requires: grpcio-python3
Requires: grpcio-python
Requires: coverage
Requires: enum34
Requires: futures
Requires: protobuf
Requires: six
Requires: wheel
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
===========
        
        Package for gRPC Python.
        
        Installation
        ------------
        
        gRPC Python is available for Linux, macOS, and Windows.
        
        From PyPI
        ~~~~~~~~~
        
        If you are installing locally...

%package python
Summary: python components for the grpcio package.
Group: Default
Requires: grpcio-python3

%description python
python components for the grpcio package.


%package python3
Summary: python3 components for the grpcio package.
Group: Default
Requires: python3-core

%description python3
python3 components for the grpcio package.


%prep
%setup -q -n grpcio-1.10.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1523015930
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
